SELECT B.ID, B.NAME, B.CNT, BT.NAME FROM BOOKS B JOIN BOOK_TYPES BT on B.TYPE_ID = BT.ID;


SELECT FINE FROM BOOKS B JOIN BOOK_TYPES BT ON BT.ID = B.TYPE_ID WHERE B.ID=11;

SELECT BOOK_ID FROM JOURNAL WHERE ID=4;

SELECT TRUNC(DATE_RET)-TRUNC(DATE_END) AS DAYS FROM JOURNAL WHERE ID=7;\

delete from BOOKS where id=1;